export const SIDEBAR_ICONS: Record<string, string> = {
  admins: 'user-switch',
  analytics: 'chart-bar',
  branches: 'building',
  categories: 'tag',
  customers: 'users',
  dashboard: 'dashboard2',
  expenses: 'expenses',
  billing: 'payments',
  products: 'unit',
  purchases: 'import-export',
  inventory: 'assignment',
  sales: 'payments',
  settings: 'settings',
  transfers: 'transfer',
}
